In [20]:
import numpy as np

In [21]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
data.shape

(10,)

In [23]:
data.reshape(2, 5)  # Преобразование в двумерный массив 2x5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
slice_data = data[1:7:2].copy()  # Срез данных
slice_data

array([1, 3, 5])

array([[(0,), (0,)],
       [(0,), (0,)]], dtype=[('a', '<i4')])